#ifndef __vectrex_compatibility_h__
#define __vectrex_compatibility_h__

// Compatibility section, defines for all gcc notation calls
#define Abs_a_b abs_a_b
#define Abs_b abs_b
#define Add_Score_a add_score_a
#define Add_Score_d add_score_d
#define Bitmask_a bitmask_a
#define Check0Ref check0ref
#define Clear_C8_RAM clear_c8_ram
#define Clear_Score clear_score
#define Clear_Sound clear_sound
#define Clear_x_256 clear_x_256
#define Clear_x_b_80 clear_x_b_80
#define Clear_x_b_a clear_x_b_a
#define Clear_x_b clear_x_b
#define Clear_x_d clear_x_d
#define Cold_Start cold_start
#define Compare_Score compare_score
#define Dec_3_Counters dec_3_counters
#define Dec_6_Counters dec_6_counters
#define Dec_Counters dec_counters
#define Delay_0 delay_0
#define Delay_1 delay_1
#define Delay_2 delay_2
#define Delay_3 delay_3
#define Delay_b delay_b
#define Delay_RTS delay_rts
#define Do_Sound_x do_sound_x
#define Do_Sound do_sound
#define Dot_d dot_d
#define Dot_here dot_here
#define Dot_ix_b dot_ix_b
#define Dot_ix dot_ix
#define Dot_List_Reset dot_list_reset
#define Dot_List dot_list
#define DP_to_C8 dp_to_c8
#define DP_to_D0 dp_to_d0
#define Draw_Grid_VL draw_grid_vl
#define Draw_Line_d draw_line_d
#define Draw_Pat_VL_a draw_pat_vl_a
#define Draw_Pat_VL_d draw_pat_vl_d
#define Draw_Pat_VL draw_pat_vl
#define Draw_VL_a draw_vl_a
#define Draw_VL_ab draw_vl_ab
#define Draw_VL_b draw_vl_b
#define Draw_VL_mode draw_vl_mode
#define Draw_VL draw_vl
#define Draw_VLc draw_vlc
#define Draw_VLcs draw_vlcs
#define Draw_VLp_7F draw_vlp_7f
#define Draw_VLp_b draw_vlp_b
#define Draw_VLp_FF draw_vlp_ff
#define Draw_VLp_scale draw_vlp_scale
#define Draw_VLp draw_vlp
#define Explosion_Snd explosion_snd
#define Get_Rise_Idx get_rise_idx
#define Get_Rise_Run get_rise_run
#define Get_Run_Idx get_run_idx
#define Init_Music_Buf init_music_buf
#define Init_Music_chk init_music_chk
#define Init_Music_x init_music_x
#define Init_Music init_music
#define Init_OS_RAM init_os_ram
#define Init_OS init_os
#define Init_VIA init_via
#define Intensity_1F intensity_1f
#define Intensity_3F intensity_3f
#define Intensity_5F intensity_5f
#define Intensity_7F intensity_7f
#define Intensity_a intensity_a
#define Intensity intensity
#define Joy_Analog joy_analog
#define Joy_Digital joy_digital
#define Mov_Draw_VL_a mov_draw_vl_a
#define Mov_Draw_VL_ab mov_draw_vl_ab
#define Mov_Draw_VL_b mov_draw_vl_b
#define Mov_Draw_VL_d mov_draw_vl_d
#define Mov_Draw_VL mov_draw_vl
#define Mov_Draw_VLc_a mov_draw_vlc_a
#define Mov_Draw_VLcs mov_draw_vlcs
#define Move_Mem_a_1 move_mem_a_1
#define Move_Mem_a move_mem_a
#define Moveto_d_7F moveto_d_7f
#define Moveto_d moveto_d
#define Moveto_ix_7F moveto_ix_7f
#define Moveto_ix_b moveto_ix_b
#define Moveto_ix_FF moveto_ix_ff
#define Moveto_ix moveto_ix
#define Moveto_x_7F moveto_x_7f
#define New_High_Score new_high_score
#define Obj_Hit obj_hit
#define Obj_Will_Hit_u obj_will_hit_u
#define Obj_Will_Hit obj_will_hit
#define Print_List_chk print_list_chk
#define Print_List_hw print_list_hw
#define Print_List print_list
#define Print_Ships_x print_ships_x
#define Print_Ships print_ships
#define Print_Str_d print_str_d
#define Print_Str_hwyx print_str_hwyx
#define Print_Str_yx print_str_yx
#define Print_Str print_str
#define Random_3 random_3
#define Random random
#define Read_Btns_Mask read_btns_mask
#define Read_Btns read_btns
#define Recalibrate recalibrate
#define Reset_Pen reset_pen
#define Reset0Int reset0int
#define Reset0Ref_D0 reset0ref_d0
#define Reset0Ref reset0ref
#define Rise_Run_Angle rise_run_angle
#define Rise_Run_Len rise_run_len
#define Rise_Run_X rise_run_x
#define Rise_Run_Y rise_run_y
#define Rot_VL_ab rot_vl_ab
#define Rot_VL_dft rot_vl_dft
#define Rot_VL_Mode_a rot_vl_mode_a
#define Rot_VL_Mode rot_vl_mode
#define Rot_VL rot_vl
#define Select_Game select_game
#define Set_Refresh set_refresh
#define Sound_Byte_raw sound_byte_raw
#define Sound_Byte_x sound_byte_x
#define Sound_Byte sound_byte
#define Sound_Bytes_x sound_bytes_x
#define Sound_Bytes sound_bytes
#define Strip_Zeros strip_zeros
#define Wait_Recal wait_recal
#define Warm_Start warm_start
#define Xform_Rise_a xform_rise_a
#define Xform_Rise xform_rise
#define Xform_Run_a xform_run_a
#define Xform_Run xform_run

#endif // __vectrex_compatibility_h__
